name:                lambda-client
synopsis:            A runtime environment for Haskell applications running on AWS Lambda.
description: |
  A runtime environment for [Haskell] applications running on [AWS Lambda]. This library is a fork
  and rewrite of the [nike/hal] library. It differs from the [nike/hal] library in the following ways:

  - It only exposes a single function that constructs a lambda
  - It has a strong emphasis on error catching and handling, exposing lambda client errors to user applications
  for post processing and reporting.
  - It aims for small dependence footprint in comparison to lambda-client by getting rid of conduit dependencies
  - It doesn't have an internal retry mechanism in case of failed HTTP connections as found in [nike/hal]
version:             0.0.1
github:              pact/lambda-runtime
license:             BSD3
author:              Nike Inc, Pact Inc, epicallan.al@gmail.com
maintainer:          epicallan.al@gmail.com, markus@pact.tax
copyright:           2018 Nike, Inc, 2021 Pact Inc
category:            Web,AWS
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings
  - DeriveFoldable
  - DeriveFunctor
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

flags:
  support_aesni:
    default: false
    manual: false
  development:
    description: Run GHC with development flags
    default: false
    manual: true

when:
  - condition: flag(development)
    then:
      ghc-options:
      - -Werror
      - -fplugin=SourceConstraints
      dependencies:
      - source-constraints ^>= 0.0.2
    else:
      ghc-options: -Wwarn

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - conversions
    - envy < 2
    - http-client
    - http-conduit
    - http-types
    - exceptions
    - mtl
    - containers
    - time
    - text

tests:
  test:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools ^>= 0.1.0

executables:
  bootstrap:
    source-dirs: example
    main: Main.hs
    dependencies:
      - base >= 4.7 && < 5
      - text
      - aeson
      - lambda-client
