name: CI

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: 2.7.3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: a-${{ matrix.os }}-${{ hashFiles(env.STACK_YAML, format('{0}.lock', env.STACK_YAML)) }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles(env.STACK_YAML, format('{0}.lock', env.STACK_YAML)) }}
          ${{ matrix.os }}-${{ matrix.ghc }}
    - name: Install dependencies
      run: stack build --test --only-dependencies
    - name: Build
      run: stack build --fast --test --no-run-tests
    - name: Run tests
      run: stack build --fast --test
